### ISSUE TITLE
Needs root rights

### ISSUE THREAD

**Issue by StefanoD** [MariusQuabeck/magic-device-tool#102]
On the usage section the snap is run without root right, but in fact it needs root rights in order to work (at least at Fedora).

**Comment by MariusQuabeck** [comment]
You are supposed to run the snap without sudo because it works fine on most systems if all necessary udev rules for fastboot/adb are in place. Unfortunately that's not the case on some distros. I've added instructions for su/sudo bash to the readme. I've also updated the todo section because we have to fix this properly. until then that's the fix for that :/

**Comment by MariusQuabeck** [comment]
https://github.com/MariusQuabeck/magic-device-tool/commit/6aab83d4d979d964c70d6191b0d17fdf586d85e7

**Comment by StefanoD** [comment]
On which Ubuntu version did you test? I tested it with 17.10 and I had to use sudo.

**Comment by MariusQuabeck** [comment]
running snaps on ubuntu does not require sudo. it's only needed if you want to flash certain devices. I have to fix this somehow. so the answer is: I've been running mdt as a snap on Ubuntu 16.04-17.10

**Comment by StefanoD** [comment]
Yes, but what's the point running your APP with user rights, if I can't flash my device?

**Comment by MariusQuabeck** [comment]
because you can flash most devices with mdt running with user rights.
