### ISSUE TITLE
 Meizu PRO5 in the Magic Device Tool

### ISSUE THREAD

**Issue by thiale1986** [MariusQuabeck/magic-device-tool#66]
Hello, Marius.
Are you forecast when the Meizu PRO5 will be included in the Magic Device Tool list? I really want to use this Ubuntu Touch system on my smartphone, I tried other tutorials (XDA) but I did not succeed.
Thanks in advance for your initiative for creating an extremely useful tool. I await your reply.
THANK YOU!!!

**Comment by MariusQuabeck** [comment]
Hello @thiale1986,

the Pro 5 is very hard to flash because it's very locked down and there are so many differences in the process depending on if you're having an official Ubuntu Edition or the Flyme OS version.
We'll try to add a way that works along with all versions but that will take some time and we are currently preparing everything to switch to the GUI version so I'll add this to our wishlist.

Kind regards
Marius

**Comment by MariusQuabeck** [comment]
We will stop supporting Ubuntu Touch in MDT soon so we are not fixing anything there anymore. Please check out the UBports installer
