### ISSUE TITLE
Parts of Magic-Device-Tool Not Working for Me

### ISSUE THREAD

**Issue by alanupson** [MariusQuabeck/magic-device-tool#69]
Congratulations and thanks for producing an excellent tool.
I used the magic-device-tool (mdt) to install Maru OS v0.4 on my Nexus 5 and it worked very well; a pleasure to use. I also used the mdt to successfully reinstall TWRP after it had got written over during some OS installations. However, I couldn’t install Lineage OS or Sailfish OS via the mdt, and the version of Ubuntu installed via mdt had several key functions (eg browser) that did not work. Have I done something wrong during the installations? If not, perhaps you could indicate that these parts of the mdt are not working in your “Functions” section of the website and add a few explanatory notes. I believe you are currently rewriting the mdt and that the new version will have a GUI; if so, could you maybe offer the option to continue with a non-GUI version, as I quite liked the interface and entering 7 for Nexus 5 and then 1 for Ubuntu, 4 for Maru OS, 7 for TWRP recovery and so on - it seemed more like magic!

**Comment by MariusQuabeck** [comment]
Hey @alanupson,

thanks for reporting this, I've tried to verify all the issues you've run into and afaik everything should be fixed by now. We have to update most of the Lineage OS download links manually as there is no redirect link to the latest build (yet). We try to update them once a week but sometimes we forget.
The cm zips for sailfish will soon all be hosted on mdt-files.com
